apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "application.labels" . | nindent 4 }}
  name: {{ .Values.app -}}-fluent-bit-cfg
data:
  {{ - include "applicatin.fluentbit_config_map" $ | nindent 2 }}